services:
  - type: web
    name: nexuscrm-api
    env: node
    plan: free
    buildCommand: bash build.sh
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        scope: build,runtime
      - key: PORT
        value: 4000
      - key: JWT_ACCESS_SECRET
        scope: build,runtime
      - key: JWT_REFRESH_SECRET
        scope: build,runtime
      - key: CORS_ORIGIN
        value: https://projeto.kreativ.ae
      - key: JWT_ACCESS_EXPIRES
        value: 15m
      - key: JWT_REFRESH_EXPIRES
        value: 7d
